Jobs4You/Models/Freelancer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4You.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Freelancer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Freelancer()
        {
            this.ApplyJobs = new HashSet<ApplyJob>();
            this.Hires = new HashSet<Hire>();
            this.Payments = new HashSet<Payment>();
            this.Skills = new HashSet<Skill>();
        }
    
        public int freelancerID { get; set; }
        public string freelancer_username { get; set; }
        public string freelancer_pass { get; set; }
        public string freelancer_phone { get; set; }
        public Nullable<int> freelancer_stat { get; set; }
        public Nullable<double> freelancer_rating { get; set; }
        public string freelancer_mail { get; set; }
        public string freelancer_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplyJob> ApplyJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hire> Hires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}

Jobs4You/Controllers/FreelancersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Jobs4You.Models;

namespace Jobs4You.Controllers
{
    public class FreelancersController : Controller
    {
        private Jobs4youEntities1 db = new Jobs4youEntities1();

        // GET: Freelancers
        public ActionResult Index()
        {
            return View(db.Freelancers.ToList());
        }

        // GET: Freelancers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Freelancer freelancer = db.Freelancers.Find(id);
            if (freelancer == null)
            {
                return HttpNotFound();
            }
            return View(freelancer);
        }

        // GET: Freelancers/Create
        /* public ActionResult Create()
         {
             return View();
         }*/


        [HttpGet]
        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(Freelancer freelancer)
        {
            if (ModelState.IsValid)
            {
                db.Freelancers.Add(freelancer);
                db.SaveChanges();
                return RedirectToAction("Login");
                //return RedirectToAction("Index");
            }

            return View(freelancer);
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(TempFreelancer tempFreelancer)
        {
            if (ModelState.IsValid)
            {
                var freelancer = db.Freelancers.Where(c => c.freelancer_mail.Equals(tempFreelancer.freelancer_mail)
                                && c.freelancer_pass.Equals(tempFreelancer.freelancer_pass)).FirstOrDefault();

                if (freelancer != null)
                {

                    //Login cookie
                    FormsAuthentication.SetAuthCookie(tempFreelancer.freelancer_mail, false);

                    //Login session
                    Session["id"] = freelancer.freelancerID;
                    Session["user_mail"] = freelancer.freelancer_mail;
                    Session["user_name"] = freelancer.freelancer_name;
                    Session["user_rating"] = freelancer.freelancer_rating;
                    Session["user_phone"] = freelancer.freelancer_phone;
                    Session["user_username"] = freelancer.freelancer_username;
                    Session["user_stat"] = freelancer.freelancer_stat;


                    string freelancerMail = (string)Session["user_mail"];
                    string freelancerName = (string)Session["user_name"];
                    string freelancerRating = (string)Session["user_rating"];
                    string freelancerPhone = (string)Session["user_phone"];
                    string freelancerUsername = (string)Session["user_username"];
                    string freelancerStat = (string)Session["user_stat"];


                    Session["user_mail"] = freelancerMail;
                    Session["user_name"] = freelancerName;
                    Session["user_rating"] = freelancerRating;
                    Session["user_phone"] = freelancerPhone;
                    Session["user_username"] = freelancerUsername;
                    Session["user_stat"] = freelancerStat;
                    Session["user_type"] = "Freelancer";


                    return RedirectToAction("Index", "Home");
                    //return Content("Login Successful!");
                }
                else
                    return Content("Login Failed");
                //return RedirectToAction("Index");
            }
            return View();
        }

        // for logout or Signout
        public ActionResult Logout()
        {
            // for cookies logout
            FormsAuthentication.SignOut();

            // for session clear
            Session.Abandon();

            return RedirectToAction("Index", "Home");
        }


        public ActionResult Profile()
        {


            return View();
        }



        // POST: Freelancers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "freelancerID,freelancer_username,freelancer_pass,freelancer_phone,freelancer_stat,freelancer_rating,freelancer_mail,freelancer_name")] Freelancer freelancer)
        {
            if (ModelState.IsValid)
            {
                db.Freelancers.Add(freelancer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(freelancer);
        }

        // GET: Freelancers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Freelancer freelancer = db.Freelancers.Find(id);
            if (freelancer == null)
            {
                return HttpNotFound();
            }
            return View(freelancer);
        }

        // POST: Freelancers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "freelancerID,freelancer_username,freelancer_pass,freelancer_phone,freelancer_stat,freelancer_rating,freelancer_mail,freelancer_name")] Freelancer freelancer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(freelancer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(freelancer);
        }

        // GET: Freelancers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Freelancer freelancer = db.Freelancers.Find(id);
            if (freelancer == null)
            {
                return HttpNotFound();
            }
            return View(freelancer);
        }

        // POST: Freelancers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Freelancer freelancer = db.Freelancers.Find(id);
            db.Freelancers.Remove(freelancer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Jobs4You/Views/Freelancers/Create.cshtml
@model Jobs4You.Models.Freelancer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Freelancer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.freelancer_username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.freelancer_username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freelancer_username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.freelancer_pass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.freelancer_pass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freelancer_pass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.freelancer_phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.freelancer_phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freelancer_phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.freelancer_stat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.freelancer_stat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freelancer_stat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.freelancer_rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.freelancer_rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freelancer_rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.freelancer_mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.freelancer_mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freelancer_mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.freelancer_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.freelancer_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freelancer_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Jobs4You/Views/Freelancers/Delete.cshtml
@model Jobs4You.Models.Freelancer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Freelancer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.freelancer_username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freelancer_username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.freelancer_pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freelancer_pass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.freelancer_phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freelancer_phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.freelancer_stat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freelancer_stat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.freelancer_rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freelancer_rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.freelancer_mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freelancer_mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.freelancer_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freelancer_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Jobs4You/Views/Freelancers/Details.cshtml
@model Jobs4You.Models.Freelancer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Freelancer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.freelancer_username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freelancer_username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.freelancer_pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freelancer_pass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.freelancer_phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freelancer_phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.freelancer_stat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freelancer_stat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.freelancer_rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freelancer_rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.freelancer_mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freelancer_mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.freelancer_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.freelancer_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.freelancerID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Jobs4You/Views/Freelancers/Index.cshtml
@model IEnumerable<Jobs4You.Models.Freelancer>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.freelancer_username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.freelancer_pass)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.freelancer_phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.freelancer_stat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.freelancer_rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.freelancer_mail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.freelancer_name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.freelancer_username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.freelancer_pass)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.freelancer_phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.freelancer_stat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.freelancer_rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.freelancer_mail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.freelancer_name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.freelancerID }) |
                @Html.ActionLink("Details", "Details", new { id = item.freelancerID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.freelancerID })
            </td>
        </tr>
    }

</table>

Jobs4You/Views/Freelancers/Login.cshtml
@model Jobs4You.Models.TempFreelancer

@{
    ViewBag.Title = "Login";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @*<div class="form-horizontal">
        <h4>Freelancer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.freelancer_mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.freelancer_mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freelancer_mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.freelancer_pass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.freelancer_pass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freelancer_pass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
                <a href="@Url.Action("SignUp","Freelancers")" class="btn btn-default" role="button">Sign Up</a>
            </div>

        </div>
    </div>*@







    <section class="login">

        <div class="limiter">
            <div class="container-login100">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="wrap-login100">
                    <div class="login100-form-title">
                        <span class="login100-form-title-1">
                            Log In (Freelancer)
                        </span>
                    </div>

                    <form class="login100-form validate-form">
                        <br>

                        <div class="wrap-input100 validate-input m-b-26" data-validate="Username is required">
                            @Html.EditorFor(model => model.freelancer_mail, new { htmlAttributes = new { @class = "input100", placeholder = "Enter E-mail"  } })
                            @Html.ValidationMessageFor(model => model.freelancer_mail, "", new { @class = "text-danger" })
                            <span class="focus-input100"></span>
                        </div>

                        <div class="wrap-input100 validate-input m-b-18" data-validate="Password is required">
                            @Html.EditorFor(model => model.freelancer_pass, new { htmlAttributes = new { @class = "input100", placeholder = "Enter Password" } })
                            @Html.ValidationMessageFor(model => model.freelancer_pass, "", new { @class = "text-danger" })
                            <span class="focus-input100"></span>
                        </div>


                        <div class="container-login100-form-btn">
                            <input type="submit" value="Login" class="login100-form-btn" />
                            <button class="signup100-form-btn">
                                <a href="@Url.Action("SignUp","Freelancers")" role="button">Sign Up</a>
                            </button>
                        </div>


                    </form>
                </div>
            </div>
        </div>
    </section>



}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Jobs4You/Views/Freelancers/Profile.cshtml
@model Jobs4You.Models.Freelancer

@{
    ViewBag.Title = "Profile";
}

@*<h2>Profile</h2>

<div>
    <h4>User_info</h4>
    <hr />
    <ul>

        <li> UserName : @HttpContext.Current.Session["user_username"] </li>
        <li> State    : @HttpContext.Current.Session["user_stat"] </li>
        <li> Phone    : @HttpContext.Current.Session["user_phone"] </li>
        <li> Rating   : @HttpContext.Current.Session["user_rating"] </li>
        <li> Name     : @HttpContext.Current.Session["user_name"] </li>
        <li> Mail     : @HttpContext.Current.Session["user_mail"] </li>


    </ul>
</div>
<p>

</p>*@


<section class="profile">
    <div class="card-container">
        <img class="round" src="~/Content/images/profile.png" alt="user" />
        <h3>@HttpContext.Current.Session["user_username"] </h3>
        <h6>@HttpContext.Current.Session["user_mail"]</h6>
        <p>@HttpContext.Current.Session["user_username"]</p>
        <p>@HttpContext.Current.Session["user_phone"]</p>
        <br>
    </div>
</section>

Jobs4You/Views/Freelancers/SignUp.cshtml
@model Jobs4You.Models.Freelancer

@{
    ViewBag.Title = "SignUp";
}

@*<h2>SignUp</h2>*@


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @*<div class="form-horizontal">
        <h4>Freelancer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.freelancer_username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.freelancer_username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freelancer_username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.freelancer_pass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.freelancer_pass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freelancer_pass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.freelancer_phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.freelancer_phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freelancer_phone, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.freelancer_stat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.freelancer_stat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.freelancer_stat, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.freelancer_rating, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.freelancer_rating, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.freelancer_rating, "", new { @class = "text-danger" })
                </div>
            </div> * ekhane '@' chilo

        <div class="form-group">
            @Html.LabelFor(model => model.freelancer_mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.freelancer_mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freelancer_mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.freelancer_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.freelancer_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.freelancer_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sign Up" class="btn btn-default" />
            </div>
        </div>
    </div>*@











    <section class="login">

        <div class="limiter">
            <div class="container-login100">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="wrap-login100">
                    <div class="login100-form-title">
                        <span class="login100-form-title-1">
                            Sign Up (Freelancer)
                        </span>
                    </div>

                    <form class="login100-form validate-form">
                        <br>

                        <!-- name -->
                        <div class="wrap-input100 validate-input m-b-26" data-validate="Name is required">
                            @Html.EditorFor(model => model.freelancer_name, new { htmlAttributes = new { @class = "input100", placeholder = "Enter Name" } })
                            @Html.ValidationMessageFor(model => model.freelancer_name, "", new { @class = "text-danger" })
                            <span class="focus-input100"></span>
                        </div>

                        <!-- username -->
                        <div class="wrap-input100 validate-input m-b-26" data-validate="Username is required">
                            @Html.EditorFor(model => model.freelancer_username, new { htmlAttributes = new { @class = "input100", placeholder = "Enter Username" } })
                            @Html.ValidationMessageFor(model => model.freelancer_username, "", new { @class = "text-danger" })
                            <span class="focus-input100"></span>
                        </div>

                        <!-- mail -->
                        <div class="wrap-input100 validate-input m-b-26" data-validate="E-mail is required">
                            @Html.EditorFor(model => model.freelancer_mail, new { htmlAttributes = new { @class = "input100", placeholder = "Enter E-mail" } })
                            @Html.ValidationMessageFor(model => model.freelancer_mail, "", new { @class = "text-danger" })
                            <span class="focus-input100"></span>
                        </div>

                        <!-- pass -->
                        <div class="wrap-input100 validate-input m-b-18" data-validate="Password is required">
                            @Html.EditorFor(model => model.freelancer_pass, new { htmlAttributes = new { @class = "input100",placeholder = "Enter Password" } })
                            @Html.ValidationMessageFor(model => model.freelancer_pass, "", new { @class = "text-danger" })
                            <span class="focus-input100"></span>
                        </div>

                        <!-- phone -->
                        <div class="wrap-input100 validate-input m-b-26" data-validate="Phone is required">
                            @Html.EditorFor(model => model.freelancer_phone, new { htmlAttributes = new { @class = "input100", placeholder = "Enter Phone" } })
                            @Html.ValidationMessageFor(model => model.freelancer_phone, "", new { @class = "text-danger" })
                            <span class="focus-input100"></span>
                        </div>




                        <div class="container-login100-form-btn">
                            <input type="submit" value="Signup" class="login100-form-btn" />
                            <button class="signup100-form-btn">
                                <a href="@Url.Action("Login","Freelancers")" role="button">Login</a>
                            </button>
                        </div>


                    </form>
                </div>
            </div>
        </div>
    </section>










}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}