Jobs4You/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Jobs4You.Models;

namespace Jobs4You.Controllers
{
    public class AdminsController : Controller
    {
        private Jobs4youEntities1 db = new Jobs4youEntities1();



        [HttpGet]
        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Admins.Add(admin);
                db.SaveChanges();
                return RedirectToAction("Login");
                //return RedirectToAction("Index");
            }

            return View(admin);
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(TempAdmin tempAdmin)
        {
            if (ModelState.IsValid)
            {
                var admin = db.Admins.Where(c => c.admin_mail.Equals(tempAdmin.admin_mail)
                                && c.admin_pass.Equals(tempAdmin.admin_pass)).FirstOrDefault();

                if (admin != null)
                {
                    FormsAuthentication.SetAuthCookie(tempAdmin.admin_mail, false);

                    Session["id"] = admin.adminID;
                    Session["user_mail"] = admin.admin_mail;
                    Session["user_username"] = admin.admin_username;


                    string adminMail = (string)Session["user_mail"];
                    string adminUsername = (string)Session["user_username"];


                    Session["user_mail"] = adminMail;
                    
                    Session["user_username"] = adminUsername;
                    Session["user_name"] = "";
                    Session["user_rating"] ="" ;
                    Session["user_phone"] = "";
                    Session["user_stat"] = "";
                    Session["user_type"] = "Admin";

                    return RedirectToAction("Index", "Home");
                    //return Content("Login Successful!");
                }
                else
                    return Content("Login Failed");
                //return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Logout()
        {
            // for cookies logout
            FormsAuthentication.SignOut();

            // for session clear
            Session.Abandon();

            return RedirectToAction("Index", "Home");
        }




        // GET: Admins
        public ActionResult Index()
        {
            return View(db.Admins.ToList());
        }

        public ActionResult Profile()
        {
            return View();
        }

        // GET: Admins/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // GET: Admins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "adminID,admin_pass,admin_username,admin_mail")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Admins.Add(admin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(admin);
        }

        // GET: Admins/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: Admins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "adminID,admin_pass,admin_username,admin_mail")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(admin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(admin);
        }

        // GET: Admins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Admin admin = db.Admins.Find(id);
            db.Admins.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Jobs4You/Controllers/jobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Jobs4You.Models;

namespace Jobs4You.Controllers
{
    public class jobsController : Controller
    {
        private Jobs4youEntities1 db = new Jobs4youEntities1();

        // GET: jobs
        public ActionResult Index()
        {
            var jobs = db.jobs.Include(j => j.Client);
            return View(jobs.ToList());
        }

        // GET: jobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            job job = db.jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: jobs/Create
        public ActionResult Create()
        {
            //if (User.Identity.IsAuthenticated)
            //{
              //  if ((string)Session["user_type"] == "Clients")
              //  {
                    //var client = db.jobs.ToList().Where(d => d.clientID == (int)Session["id"]); 
                ViewBag.clientID = new SelectList(db.Clients, "clientID", "client_mail");

               // }
         //   }

            return View();
        }

        // POST: jobs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "jobID,clientID,pricing,details,duration")] job job)
        {
            if (User.Identity.IsAuthenticated)
            {


                if (ModelState.IsValid)
                {
                    job.clientID = (int)Session["id"];
                    db.jobs.Add(job);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

               // ViewBag.clientID = new SelectList(db.Clients, "clientID", "client_username", job.clientID);
                return View();
            }
            else
            {
               return RedirectToAction("Index", "Home");
            }

        }

        // GET: jobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            job job = db.jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            ViewBag.clientID = new SelectList(db.Clients, "clientID", "client_username", job.clientID);
            return View(job);
        }

        // POST: jobs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "jobID,clientID,pricing,details,duration")] job job)
        {
            if (ModelState.IsValid)
            {
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.clientID = new SelectList(db.Clients, "clientID", "client_username", job.clientID);
            return View(job);
        }




        public ActionResult Apply(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            job job = db.jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            // ViewBag.clientID = new SelectList(db.Clients, "clientID", "client_username", job.clientID);
            if (User.Identity.IsAuthenticated)
            {


                if (ModelState.IsValid)
                {
                    // applyJob.freelancerID = (int)Session["id"];
                    int freelancerId = (int)Session["id"];
                    int jobId = job.jobID;

                    using (var ctx = new Jobs4youEntities1())
                    {
                        var jobs = ctx.ApplyJobs
                                        .SqlQuery("Select * from ApplyJobs where jobID="+jobId+" and freelancerID="+freelancerId)
                                        .FirstOrDefault();

                        if(jobs==null)
                        ctx.Database.ExecuteSqlCommand("insert into ApplyJobs (jobID,freelancerID) values('" + jobId.ToString() + "','" + freelancerId.ToString() + "')");
                    }
                    

                 //   using (var ctx = new Jobs4youEntities1())
                 //   {
                        

                  //  }

                    return RedirectToAction("Index", "ApplyJobs");
                }

                ViewBag.clientID = new SelectList(db.Clients, "clientID", "client_username", job.clientID);
                return RedirectToAction("Index", "ApplyJobs");
            }
            else
            {
                return RedirectToAction("Index", "ApplyJobs");
            }
        }

        // POST: jobs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.





        // GET: jobs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            job job = db.jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            job job = db.jobs.Find(id);
            db.jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }





        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Jobs4You/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/navbar.css" rel="stylesheet" />

    <!--Index page er elements -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @*<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">*@
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">


    <!-- custom index page -->
    <link href="@Url.Content("~/Content/aos.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/custom.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/navbar.css")" rel="stylesheet" type="text/css" />


    @*<style>
            html, body, h1, h2, h3, h4 {
                font-family: "Lato", sans-serif
            }

            .mySlides {
                display: none
            }

            .w3-tag, .fa {
                cursor: pointer
            }

            .w3-tag {
                height: 15px;
                width: 15px;
                padding: 0;
                margin-top: 6px
            }
        </style>*@
    <!--Index page er elements -->


    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>


    <!-- ============================================================ navigation bar ============================================================ -->



    <nav class="navbar navbar-light navbar-expand-md bg-faded justify-content-center fixed-top">
        <div class="container">
            <a class="navbar-brand d-flex w-25 me-auto" href="@Url.Action("Index", "Home")">  <img src="~/Content/images/logo.png" alt="Phishing Detect" class="mx-auto"> </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsingNavbar3">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">

                <ul class="nav navbar-nav ms-auto w-100 justify-content-end">

                    @if (User.Identity.IsAuthenticated)
                    {
                        if ((string)Session["user_type"] == "Admin")
                        {
                            <li>
                                <a class="nav-link" href="@Url.Action("Index", "ApplyJobs")">Applicants List</a>
                            </li>
                            <li>
                                <a class="nav-link" href="@Url.Action("Index", "Jobs")">Jobs</a>
                            </li>
                            <li>
                                <a class="nav-link" href="@Url.Action("Index", "Clients")">Clients</a>
                            </li>
                            <li>
                                <a class="nav-link" href="@Url.Action("Index", "Freelancers")">Freelancers</a>
                            </li>
                            <li>
                                <a class="nav-link" href="@Url.Action("Index", "Payments")">Payments</a>
                            </li>
                            <li>
                                <a class="nav-link" href="@Url.Action("Profile", "Admins")">Profile</a>
                            </li>
                            <li>@Html.ActionLink("Logout", "Logout", "Admins")</li>

                            //  <li>
                            //      <a class="nav-link" href="@Url.Action("Index", "Invoices")">Invoices</a>
                            //  </li>
                        }

                        else if ((string)Session["user_type"] == "Freelancer")
                        {

                            <li>
                                <a class="nav-link" href="@Url.Action("About", "Home")">About us</a>
                            </li>
                            <li>
                                <a class="nav-link" href="@Url.Action("Index","jobs")">Available Jobs</a>
                            </li>
                            <li>
                                <a class="nav-link" href="@Url.Action("Index", "ApplyJobs")">Applied Jobs</a>
                            </li>
                            <li>
                                <a class="nav-link" href="@Url.Action("index", "Skills")">Skills</a>
                            </li>
                            <li>
                                <a class="nav-link" href="@Url.Action("Index", "Invoices")">Your Payments</a>
                            </li>
                            <li>
                                <a class="nav-link" href="@Url.Action("Profile", "Freelancers")">Profile</a>
                            </li>

                            <li>@Html.ActionLink("Logout", "Logout", "Freelancers")</li>
                        }
                        else if ((string)Session["user_type"] == "Client")
                        {

                            <li>
                                <a class="nav-link" href="@Url.Action("About", "Home")">About us</a>
                            </li>
                            <li>
                                <a class="nav-link" href="@Url.Action("Index","Jobs")">Your Jobs</a>
                            </li>
                            <li>
                                <a class="nav-link" href="@Url.Action("Index", "ApplyJobs")">Applications</a>
                            </li>
                            <li>
                                <a class="nav-link" href="@Url.Action("Index", "Invoices")">Your Payments</a>
                            </li>
                            <li>
                                <a class="nav-link" href="@Url.Action("Profile", "Clients")">Profile</a>
                            </li>
                            <li>@Html.ActionLink("Logout", "Logout", "Clients")</li>
                        }

                        else
                        {
                            @*<li>
                    <a class="nav-link" href="#">Categories</a>
                </li>*@
                            <li>
                                <a class="nav-link" href="@Url.Action("About", "Home")">About us</a>
                            </li>
                            @*<li>
                    <a class="nav-link" href="#">Offers</a>
                </li>*@

                        }
                    }
                    else
                    {
                        @*<li>
                <a class="nav-link" href="#">Categories</a>
            </li>*@

                        <li>
                            <a class="nav-link" href="@Url.Action("About", "Home")">About us</a>
                        </li>
                        @*<li>
                <a class="nav-link" href="#">Offers</a>
            </li>*@
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-log-in"></span> Login / Sign Up</a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Login","Clients")" style="font-weight:bold;">Clients</a></li>
                                <li><a href="@Url.Action("Login","Freelancers")" style="font-weight:bold;">Freelancers</a></li>


                            </ul>
                        </li>


                    }

                    @*if user is authenticated then this item will be visible*@
                    @*
        @if (User.Identity.IsAuthenticated)
        {
            if ((string)Session["user_type"] == "Admin")
            {

            }


            <li>@Html.ActionLink("Logout", "Logout", "Clients")</li>
            <li>@User.Identity.Name</li>

        }
        else
        {
            <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-log-in"></span> Login / Sign Up</a>
                <ul class="dropdown-menu">
                    <li><a href="@Url.Action("Login","Clients")" style="font-weight:bold;">Clients</a></li>
                    <li><a href="@Url.Action("Login","Freelancers")" style="font-weight:bold;">Freelancers</a></li>


                </ul>
            </li>
        }*@

                </ul>
            </div>
        </div>
    </nav>


    <!-- ======================================================================================================================================= -->

    <div class="body-content" id="container-body">
        @RenderBody()
        @*<hr />
        <footer class="w3-container w3-padding-32 w3-light-grey w3-center">

            <a href="#" class="w3-button w3-black w3-margin"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
            <div class="w3-xlarge w3-section">
                <i class="fa fa-facebook-official w3-hover-opacity"></i>
                <i class="fa fa-instagram w3-hover-opacity"></i>
                <i class="fa fa-snapchat w3-hover-opacity"></i>
                <i class="fa fa-pinterest-p w3-hover-opacity"></i>
                <i class="fa fa-twitter w3-hover-opacity"></i>
                <i class="fa fa-linkedin w3-hover-opacity"></i>
            </div>
            <p>ⒸAll Rights Reserved.Jobs4You2021</p>
        </footer>*@

        <div class="jumbotron jumbotron-fluid" id="copyright">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col-md-6 text-white align-self-center text-center text-md-left my-2">
                        ⒸAll Rights Reserved.Jobs4You2021.
                    </div>
                    <div class="col-md-6 align-self-center text-center text-md-right my-2" id="social-media">
                        <a href="#" class="d-inline-block text-center ml-2">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                        </a>
                        <a href="#" class="d-inline-block text-center ml-2">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </a>
                        <a href="#" class="d-inline-block text-center ml-2">
                            <i class="fa fa-medium" aria-hidden="true"></i>
                        </a>
                        <a href="#" class="d-inline-block text-center ml-2">
                            <i class="fa fa-linkedin" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>



    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        function preventBack() { window.history.forward(); }
        setTimeout("preventBack()", 0);
        window.onunload = function () { null };
    </script>
</body>
</html>